---
- name: Create cloudadmins group
  group:
    name: cloudadmins
    state: present
    
- name: Create user accounts
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
    state: "{{ item.state }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /home/srujal/.ssh
    ssh_key_comment: "{{ item.username }}"
    password: ""
    shell: /bin/bash
  loop: "{{ users }}"

- name: Add SSH keys for users
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file','/home/srujal/.ssh') }}"
    state: present
  loop: "{{ users }}"

- name: Validate the sudoers file before saving, uncomment 
  lineinfile:
    path: "{{ item.path }}"
    line: ' %cloudadmins ALL=(ALL) NOPASSWD: ALL'
    create: yes
    validate: "{{ item.validate }}"
  loop: "{{ sudoersUpdate }}"
...
